import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>Header</h1>
        </header>
        <nav>
          <p>Links to places in idk a list</p>
          <ol>
            <li>---Link 1</li>
            <li><Link href="/">Home</Link></li>
          </ol>
        </nav>
        {children}
        <footer>
          <h2>Here is the footer</h2>
        </footer>
      </body>
    </html>
  );
}
